server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: auth-service
  security:
    jwt:
      secret: ${JWT_SECRET:8y/B?E(H+MbQeThWmZq4t6w9z$C&F)J@NcRfUjXn2r5u8x/A%D*G-KaPdSgVkYp3}
      expiration: 86400000 # 24 hours in milliseconds
      refresh-token:
        expiration: 604800000 # 7 days in milliseconds

jwt:
  secret: ${JWT_SECRET:8y/B?E(H+MbQeThWmZq4t6w9z$C&F)J@NcRfUjXn2r5u8x/A%D*G-KaPdSgVkYp3}
  expiration: 86400000 # 24 hours in milliseconds
  refresh-token:
    expiration: 604800000 # 7 days in milliseconds

cors:
  allowed-origins: 
    - "http://localhost:*"
    - "http://127.0.0.1:*"
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,HEAD
  allowed-headers: "*"
  exposed-headers: 
    - "Authorization"
    - "Content-Type"
  allow-credentials: true
  max-age: 3600

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.data.r2dbc: DEBUG
    io.r2dbc: DEBUG
    com.celebrating.auth: DEBUG 