server:
  port: 8084

spring:
  application:
    name: search-service
  elasticsearch:
    uris: http://localhost:9200

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*" 