server:
  port: 8082

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://197.254.53.252:5432/celebratedb?sslmode=disable
    username: celebrate
    password: celebrate123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.postgresql: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://197.254.53.252:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: 197.254.53.252

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always 