package com.celebrating.post.model;

public enum CelebrationType {
    PERSONAL_ACHIEVEMENT,
    CAREER_MILESTONE,
    EDUCATIONAL_SUCCESS,
    HEALTH_FITNESS,
    RELATIONSHIP_MILESTONE,
    CREATIVE_ACCOMPLISHMENT,
    BUSINESS_SUCCESS,
    COMMUNITY_SERVICE,
    TRAVEL_ADVENTURE,
    LIFE_EVENT,
    OTHER
} 