spring:
  application:
    name: API-GATEWAY
  cloud:
    config:
      enabled: false
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:8080"
              - "http://127.0.0.1:3000"
              - "http://localhost"
              - "http://localhost:58138"
              - "http://127.0.0.1:58138"
              - "app://celebrate"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders:
              - "Authorization"
            allowCredentials: true
            maxAge: 3600
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - PreserveHostHeader
            - RemoveRequestHeader=Cookie
            - RemoveRequestHeader=Set-Cookie
            - RewritePath=/api/auth/(?<segment>.*), /${segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /${segment}
            - AddRequestHeader=X-Forwarded-Prefix, /api/users
            - JwtAuthentication
        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/posts/**
          filters:
            - RewritePath=/api/posts/(?<segment>.*), /${segment}
            - AddRequestHeader=X-Forwarded-Prefix, /api/posts
            - JwtAuthentication
        - id: messaging-service
          uri: lb://MESSAGING-SERVICE
          predicates:
            - Path=/api/messages/**
          filters:
            - RewritePath=/api/messages/(?<segment>.*), /${segment}
            - AddRequestHeader=X-Forwarded-Prefix, /api/messages
            - JwtAuthentication
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
        - id: news-feed-service
          uri: lb://news-feed-service
          predicates:
            - Path=/api/news-feed/**
        - id: moderation-service
          uri: lb://moderation-service
          predicates:
            - Path=/api/moderation/**
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/api/search/**
        - id: award-service
          uri: lb://award-service
          predicates:
            - Path=/api/awards/**

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG
    io.netty: DEBUG
    org.springframework.web.cors: DEBUG
    reactor.netty.http.client: DEBUG 

jwt:
  secret: 8y/B?E(H+MbQeThWmZq4t6w9z$C&F)J@NcRfUjXn2r5u8x/A%D*G-KaPdSgVkYp3 