spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:8080"
              - "http://127.0.0.1:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders:
              - "Authorization"
            allowCredentials: true
            maxAge: 3600
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/posts/**
          filters:
            - RewritePath=/api/posts/(?<segment>.*), /${segment}
            - AddRequestHeader=X-Forwarded-Prefix, /api/posts
        - id: messaging-service
          uri: lb://messaging-service
          predicates:
            - Path=/api/messages/**
          filters:
            - RewritePath=/api/messages/(?<segment>.*), /${segment}
            - AddRequestHeader=X-Forwarded-Prefix, /api/messages
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
        - id: news-feed-service
          uri: lb://news-feed-service
          predicates:
            - Path=/api/news-feed/**
        - id: moderation-service
          uri: lb://moderation-service
          predicates:
            - Path=/api/moderation/**
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/api/search/**
        - id: award-service
          uri: lb://award-service
          predicates:
            - Path=/api/awards/**

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG
    io.netty: DEBUG
    org.springframework.web.cors: DEBUG
    reactor.netty.http.client: DEBUG 