spring:
  application:
    name: monitoring-service
  config:
    import: "optional:configserver:"
  thymeleaf:
    cache: false

server:
  port: 8094
  servlet:
    context-path: /monitor

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: 197.254.53.252

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.web: DEBUG
    com.celebrating.monitoring: DEBUG 